name: scanpy
channels:
  - defaults
dependencies:
  - pip=24.0
  - python=3.11.7
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - anndata==0.10.8
      - array-api-compat==1.8
      - attrs==23.2.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - chex==0.1.86
      - click==8.1.7
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - docrep==0.3.2
      - et-xmlfile==1.1.0
      - etils==1.9.2
      - filelock==3.15.4
      - flax==0.8.5
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - h5py==3.11.0
      - harmonypy==0.0.10
      - idna==3.7
      - igraph==0.11.6
      - imageio==2.34.2
      - importlib-resources==6.4.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - leidenalg==0.10.2
      - lightning==2.1.4
      - lightning-utilities==0.11.6
      - llvmlite==0.43.0
      - louvain==0.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - mudata==0.2.4
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numba==0.60.0
      - numpy==1.26.4
      - numpyro==0.15.1
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - optax==0.2.3
      - orbax-checkpoint==0.5.22
      - packaging==24.1
      - pandas==2.2.2
      - patsy==0.5.6
      - pillow==10.4.0
      - protobuf==5.27.2
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.3.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - rich==13.7.1
      - scanpy==1.10.2
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - scvi-tools==1.1.5
      - seaborn==0.13.2
      - session-info==1.0.0
      - six==1.16.0
      - statsmodels==0.14.2
      - stdlib-list==0.10.0
      - sympy==1.13.1
      - tensorstore==0.1.63
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - toolz==0.12.1
      - torch==2.4.0
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.4
      - umap-learn
      - urllib3
      - yarl
      - zipp
